name: iupac2struct
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - tqdm
  - jupyter
  - rdkit
  - pip
  - pip:
      - torch==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - torchaudio==2.8.0+cu128
      - --extra-index-url https://download.pytorch.org/whl/cu128